### ISSUE TITLE
Complete Current load

### ISSUE THREAD

**Issue by thboehm** [snitzelweck92/homeassistant_alphaess_modbus_tcp#11]
Hi,

I'm not able to find right sensors for "current complete Load"

I have tried this, but here the power from PV is missing. But I can't find the right sensor for current PV power:
      state: "{{ (states('sensor.alpha_ess_total_power_grid') |float - states('sensor.alpha_ess_total_power_battery') | float) }}"

I hope you have also tried to get current load and you can share the right solution.

Thanks & BR

**Comment by snitzelweck92** [comment]
Hey,

You find the power of all PV Strings summarized in following
template-sensor:
sensor.alpha_ess_actual_production

Is this what you want?

To see what the house is using as complete power, i think you have to check
what the Inverter is doing plus the grid consumption (can be negative by a
higher production than consumption).

For myself I have a Shelly 3em for measuring the house consumption.


thboehm ***@***.***> schrieb am Mo., 6. Nov. 2023, 14:48:

**Comment by thboehm** [comment]
Hi,

unfortunately sensor.alpha_ess_actual_production is not the right one.

There should be something like sensor.alpha_ess_actual_pv_usage, but it is not there :-(

Maybe some "sub"-calculation like "Production - (Battery charge + Load to Grid)". But there is no power sensor for Load to Grid)
      sensor.alpha_ess_actual_production - (sensor.alpha_ess_total_power_battery + ???)

Perhaps any other idea?

**Comment by snitzelweck92** [comment]
sensor.alpha_ess_actual_production is showing the current power from the panels (DC side).
sensor.pv_totalpower_grid shows the consumption from/to grid (when there is a consumption, then the value is positive. Is there a feed to grid, the value is negative.
sensor.pv_totalpower_inverter shows the poweroutput of the inverter (converted DC from panels to AC, the battery consumption is here already substracted, because this is DC). 

So when you want to know, what the consumption of the house is (AC-Consumption) you have to check the calculate it:
consumptionHouse = sensor.pv_totalpower_inverter + sensor.pv_totalpower_grid 

I will update the template-sensors with adding this sensor. 
But you are free to provide a example what you want. 

I'm reading my house consumption with a Shelly 3EM because it is more accurate. 
But they seems more than identically. 

So you can check it out with release 2.1.0.

**Comment by thboehm** [comment]
Hi,

thank you very much.
I have made it like this:
```
[core-ssh packages]$ grep -B 4 -A 5 alpha_ess_current_consume_home integration_alpha_ess.yaml |grep -v '#state'
#Sensor templates
template:
  - sensor:
      #Current Power consumption of the home
      - name: alpha_ess_current_consume_home
        unique_id: alpha_ess_current_consume_home
        unit_of_measurement: "W"
        state: "{{ (states('sensor.alpha_ess_total_power_grid') | float + states('sensor.alpha_ess_total_power_inverter') | float) }}"
      #Total consumption of the home
[core-ssh packages]$ 

```

BR
